### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/packages-1#8]
- [x] update ntfs-3g
- [x] libsodium
- [x] deal with ffmpeg changes
- [x] ffmpeg: drop ARM thumb instruction set, may have bad performance
- [x] rework redsocks init script
